// Emits dist/_headers for Cloudflare Workers static assets after a build.
//
// Workers parses this file and applies its rules to asset responses rather
// than serving it. worker/index.ts (wrangler.jsonc `main`) hands every app
// request to the ASSETS binding, so these headers cover every response the
// app sends; the MCP hostname is answered by the Worker itself.
//
// The CSP is generated rather than checked in because two parts of it change
// with the build: the hash of the inline theme bootstrap in index.html, and
// the API origin the app is configured against.
//
// Pass a directory as the first argument to read and write somewhere other
// than dist/ (a scratch build).
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";
import { loadEnv } from "vite";

const dist = resolve(process.cwd(), process.argv[2] || "dist");
const html = readFileSync(resolve(dist, "index.html"), "utf8");

// index.html runs one inline script so the first paint is already in the right
// theme. Allow exactly that script by hash — never 'unsafe-inline'.
const inlineScripts = [
  ...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi),
];
const scriptHashes = inlineScripts.map(
  ([, body]) =>
    `'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`,
);

// Match Vite's production API default and optional environment override.
// The same resolution Vite used for the bundle: .env files plus the process
// environment. Reading process.env alone would miss .env.local and emit a CSP
// that blocks the API the app was actually built against.
const env = loadEnv(
  process.env.NODE_ENV || "production",
  process.cwd(),
  "VITE_",
);
// Mirrors the default in vite.config.ts: a build with no VITE_API_URL talks to
// the hosted API, so its policy must admit that origin. A self-hosted build
// sets VITE_API_URL and gets only its own origin.
const configured = env.VITE_API_URL?.trim() || "https://api.wireal.co";
// The Files tab reads which files a linked commit changed from GitHub. The
// request carries no credentials, and a blocked, private or rate-limited answer
// simply leaves that list unavailable. Turnstile also needs its challenge
// origin.
const connect = [
  "'self'",
  "https://api.github.com",
  "https://challenges.cloudflare.com",
];
// Cloudflare Web Analytics, admitted only when the deployment uses it. The
// script loads from static.cloudflareinsights.com and reports page views to
// cloudflareinsights.com/cdn-cgi/rum. Two ways to turn it on:
// - VITE_CF_WEB_ANALYTICS=edge: the Cloudflare dashboard's automatic setup
//   injects the beacon <script> into HTML responses at the edge, after the
//   build, so the built index.html never contains it and the policy has to
//   admit it anyway. The hosted wireal.co build uses this.
// - VITE_CF_BEACON_TOKEN: vite.config.ts writes the tag into index.html
//   itself, which is detected below.
// A build with neither sends nothing to Cloudflare Insights and its policy
// does not allow it.
const beaconScript = "https://static.cloudflareinsights.com";
const beaconReport = "https://cloudflareinsights.com";
const scripts = ["'self'", "https://challenges.cloudflare.com"];
const beacon = html.includes(`src="${beaconScript}/beacon.min.js"`);
const analyticsMode = env.VITE_CF_WEB_ANALYTICS?.trim() || "";
if (analyticsMode && analyticsMode !== "edge")
  throw new Error('VITE_CF_WEB_ANALYTICS must be "edge" or unset.');
const analytics = beacon || analyticsMode === "edge";
if (analytics) {
  scripts.push(beaconScript);
  connect.push(beaconReport);
}
const images = [
  "'self'",
  "data:",
  "blob:",
  "https://avatars.githubusercontent.com",
];
if (configured) {
  let origin;
  try {
    const url = new URL(configured);
    if (
      url.protocol !== "https:" ||
      url.pathname !== "/" ||
      url.search ||
      url.hash ||
      url.username ||
      url.password
    )
      throw new Error("Expected HTTPS origin");
    origin = url.origin;
  } catch {
    throw new Error("VITE_API_URL must be a valid HTTPS API origin.");
  }
  connect.push(origin);
  images.push(origin);
}

const csp = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  `script-src ${[...scripts, ...scriptHashes].join(" ")}`,
  "frame-src https://challenges.cloudflare.com",
  // React writes style attributes constantly (label transforms, orb colours),
  // which style-src governs. Scripts stay hash-pinned.
  "style-src 'self' 'unsafe-inline'",
  `img-src ${images.join(" ")}`,
  "font-src 'self'",
  `connect-src ${connect.join(" ")}`,
  "upgrade-insecure-requests",
].join("; ");

const headers = `# Generated by scripts/cloudflare-headers.mjs — do not edit by hand.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# Vite fingerprints these filenames, so they can be cached forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(resolve(dist, "_headers"), headers);
console.log(
  `cloudflare-headers: wrote ${relative(process.cwd(), resolve(dist, "_headers"))} (${scriptHashes.length} inline script hash${
    scriptHashes.length === 1 ? "" : "es"
  }${configured ? `, API ${new URL(configured).host}` : ", no API origin"}${
    beacon
      ? ", build-time Web Analytics beacon"
      : analytics
        ? ", edge-injected Web Analytics"
        : ""
  })`,
);
